"""Pydantic models shared across API endpoints and services."""

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, field_validator


class CitationStatus(str, Enum):
    """Enumeration of citation verification states."""

    verified = "verified"
    ghost = "ghost"
    unverified = "unverified"


class ParsedDocument(BaseModel):
    """Structured representation of a parsed academic document."""

    full_text: str
    abstract: str
    sections: dict[str, str]
    references: list[str]
    word_count: int = Field(ge=0)


class CitationResult(BaseModel):
    """Verification output for a single citation entry."""

    raw: str
    doi: str | None = None
    status: CitationStatus
    title: str | None = None
    year: int | None = None


class CitationSummary(BaseModel):
    """Aggregated citation verification metrics."""

    verified: int = Field(ge=0)
    ghost: int = Field(ge=0)
    unverified: int = Field(ge=0)
    total: int = Field(ge=0)
    items: list[CitationResult]


class RecentPaper(BaseModel):
    """One recent paper from the matched journal."""

    title: str
    year: int | None = None


class JournalMatch(BaseModel):
    """Journal fit and retrieval details for the manuscript."""

    found: bool
    target: str
    openalex_name: str | None = None
    works_count: int | None = None
    recent_papers: list[RecentPaper] = Field(default_factory=list)


class Mood(str, Enum):
    """Editor mood values the app can render."""

    furious = "furious"
    skeptical = "skeptical"
    unimpressed = "unimpressed"
    neutral = "neutral"
    interested = "interested"
    delighted = "delighted"


class Severity(str, Enum):
    """Rejection-reason severity values the app can colour."""

    desk_reject = "desk_reject"
    major = "major"
    minor = "minor"


class SectionScore(BaseModel):
    """Evaluation information for one paper section.

    Mode a fills issue and fix. Mode b fills strength and weakness.
    All four are optional so either schema validates.
    """

    score: int = Field(ge=0, le=100)
    issue: str | None = None
    fix: str | None = None
    strength: str | None = None
    weakness: str | None = None

    @field_validator("score", mode="before")
    @classmethod
    def clamp_score(cls, value: object) -> int:
        """Keep a bad model score inside the range the app draws."""
        if isinstance(value, bool) or not isinstance(value, (int, float, str)):
            return 0
        try:
            number = int(value)
        except ValueError:
            return 0
        return max(0, min(100, number))


class RejectionReason(BaseModel):
    """One concrete reason the manuscript may be rejected."""

    reason: str = "Unspecified issue"
    severity: Severity = Severity.major
    fix: str = ""

    @field_validator("severity", mode="before")
    @classmethod
    def coerce_severity(cls, value: object) -> str:
        """Fall back to major when the model invents a severity."""
        if isinstance(value, str) and value in {item.value for item in Severity}:
            return value
        return Severity.major.value


class AnalysisResult(BaseModel):
    """Overall paper analysis generated by the backend pipeline."""

    mood: Mood = Mood.neutral
    mood_score: int = Field(ge=0, le=100)
    verdict: str
    oracle_letter: str
    sections: dict[str, SectionScore]
    rejection_reasons: list[RejectionReason]
    novelty_assessment: str
    journal_fit: str
    provider_used: str

    @field_validator("mood", mode="before")
    @classmethod
    def coerce_mood(cls, value: object) -> str:
        """Fall back to neutral when the model returns an unknown mood."""
        if isinstance(value, str) and value in {item.value for item in Mood}:
            return value
        return Mood.neutral.value

    @field_validator("mood_score", mode="before")
    @classmethod
    def clamp_mood_score(cls, value: object) -> int:
        """Keep the score ring inside 0–100."""
        if isinstance(value, bool) or not isinstance(value, (int, float, str)):
            return 0
        try:
            number = int(value)
        except ValueError:
            return 0
        return max(0, min(100, number))


class PaperMeta(BaseModel):
    """Timing and document stats shown under the report."""

    word_count: int = Field(ge=0)
    sections_found: list[str]
    references_found: int = Field(ge=0)
    mode: str
    processing_ms: int = Field(ge=0)


class AnalysisPaperResponse(BaseModel):
    """Top-level response object for paper analysis API results."""

    analysis: AnalysisResult
    citations: CitationSummary
    journal: JournalMatch
    meta: PaperMeta


class AnalyseRequest(BaseModel):
    """Request body for the analysis endpoint."""

    abstract: str
    sections: dict[str, str]
    target_journal: str
    citation_summary: str
    journal_data: dict[str, Any] = Field(default_factory=dict)
    mode: str = "a"
